import type { Metadata } from "next";
import "./globals.css";
import NextAuthProvider from "../components/providers/nextauth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

import { Plus_Jakarta_Sans } from "next/font/google";
const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: {
    default: "100xCoding",
    template: "%s - 100xCoding",
  },
  description: "Generated by create next app",
};
import { Toaster } from "sonner";
import SWRProvider from "@/components/providers/swr-provider";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn("font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Toaster position="top-right" closeButton richColors />
          <NextAuthProvider>
            <SWRProvider>{children}</SWRProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
